import { Inter } from 'next/font/google'
import '../css/plugins.css';
import '../css/style.css';
import '../css/templete.css';
import '../css/skin/skin-1.css';
import '../plugins/slick/slick.min.css';
import '../plugins/slick/slick-theme.min.css';
import Header from './layout/Header';
import Footer from './layout/Footer';
import { authOptions } from './api/auth/[...nextauth]/authOptions';
import { getServerSession } from 'next-auth';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from '@/components/Navbar';
import AuthProvider from '@/provider/AuthProvider';
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'HireLab',
  description: 'Generated by create next app',
}
// 1885314849
export default async function RootLayout({ children }) {
 const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ToastContainer />
        <AuthProvider>
          <Header session={session} />        
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}

